### PR TITLE
Update test and production URLs to use chasepaymentech.com for TLS 1.2 and SHA-2

### PR DESCRIPTION
**Pull request by pixelchutes**
New Chase Paymentech Test/Production URLs for upcoming TLS v1.2 and SHA-2 roll-out after 2017-09-30.

> To ensure uninterrupted processing of payments **after September 30, 2017**, please update your systems with enhanced internet security standards TLS v1.2 and SHA-2. Please refer to previous communications sent to you or consult your Chase Merchant Services relationship manager to ensure compliance with these new standards.

### CODE REVIEW

**Comment by pixelchutes** [comment]
sha-2

**Comment by pixelchutes** [comment]
Build failing since targeting `precise` dist for php 5.3, but no longer supported in Travis.

See https://docs.travis-ci.com/user/reference/trusty#PHP-images

**Comment by mmacaulay** [comment]
Bumped PHP versions on master if you want to merge those in and try the build again. Thanks for the fix!

**Comment by pixelchutes** [comment]
Hi @mmacaulay -- As part of our planning around the 9/30 date, I wanted to touch base on this PR to see if it would be merged in time for additional testing before then?

Also, I'm not clear on who maintains updating Packagist? TWG or @jeremib ?

**Comment by jeremib** [comment]
Unfortunately I only have a forked version of this, not the maintainer of the original one on packagist.

**Comment by mmacaulay** [comment]
Hi @pixelchutes and @jeremib, I apologize for not getting back to you on this sooner. It's been a busy last few days around here. I'll merge this in now.

It's also worth mentioning that TWG originally built this library for a client project a while back and we're no longer actively using it, so it might make more sense to standardize on @jeremib's fork going forward.

**Pull request merged**
